services:
  # PostgreSQL Database
  postgres:
    image: postgres:17-alpine
    container_name: iran-market-db-v2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres123}
      POSTGRES_DB: iran_market_data
    volumes:
      - iran_market_postgres_data:/var/lib/postgresql/data
      - ./database/create_tables.sql:/docker-entrypoint-initdb.d/01-create-tables.sql:ro
    ports:
      - "5432:5432"  # Expose database port for local API access
    networks:
      - market-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-iran_market_data}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Python Application with auto-reload
  app:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: iran-market-app-v2
    environment:
      # Database configuration
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME:-iran_market_data}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres123}
      # API Keys - Set these in your environment or .env file
      BRSAPI_FREE_KEY: ${BRSAPI_FREE_KEY}
      BRSAPI_PRO_KEY: ${BRSAPI_PRO_KEY}
      # API Configuration
      API_BATCH_SIZE: ${API_BATCH_SIZE:-10}
      API_DELAY_SECONDS: ${API_DELAY_SECONDS:-1}
      MAX_RETRIES: ${MAX_RETRIES:-3}
      # Python settings for better output
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1
    volumes:
      # Mount entire project for auto-reload
      - ./:/app:rw
      # Exclude cache directories
      - /app/__pycache__
      - /app/.git
      - /app/.idea
      - /app/.vscode
    ports:
      - "8000:8000"  # API server port
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - market-network
    # Use watchmedo for auto-reload on code changes - start in interactive mode
    command: >
      python -m uvicorn trading_platform.api.main:app 
      --host 0.0.0.0 
      --port 8000 
      --reload
    stdin_open: true
    tty: true
    restart: unless-stopped

  # React Frontend Application
  frontend:
    build:
      context: ./web_platform
      dockerfile: Dockerfile
    container_name: iran-market-frontend-v2
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true  # For hot reload on Windows
      - WATCHPACK_POLLING=true
    volumes:
      # Mount source code for hot reload
      - ./web_platform/frontend:/app:rw
      # Exclude node_modules to use container's version
      - /app/node_modules
    ports:
      - "3000:3000"  # Access frontend at http://localhost:3000
    networks:
      - market-network
    depends_on:
      - app
    stdin_open: true
    tty: true
    restart: unless-stopped

  # pgAdmin for database management - Exposed on port 5050
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: iran-market-pgadmin-v2
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin123}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    volumes:
      - iran_market_pgadmin_data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json:ro
    ports:
      - "5050:80"  # Access pgAdmin at http://localhost:5050
    networks:
      - market-network
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

networks:
  market-network:
    driver: bridge
    name: iran-market-network

volumes:
  iran_market_postgres_data:
    name: iran_market_postgres_data
  iran_market_pgadmin_data:
    name: iran_market_pgadmin_data